CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Language" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LanguageName" text NOT NULL,
    "LanguageCode" text NULL,
    CONSTRAINT "PK_Language" PRIMARY KEY ("Id")
);

CREATE TABLE "Role" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "EnteredBy" integer NOT NULL,
    "EnteredDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" integer NOT NULL,
    "LastUpdated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "SystemSetting" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "EnteredBy" integer NOT NULL,
    "EnteredDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" integer NOT NULL,
    "LastUpdated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_SystemSetting" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text NULL,
    "Name" text NULL,
    "Password" text NOT NULL,
    "EnteredBy" integer NOT NULL,
    "EnteredDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" integer NOT NULL,
    "LastUpdated" timestamp without time zone NOT NULL,
    "RefreshToken" text NULL,
    "RefreshTokenExpiryTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "Amendment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Author" text NULL,
    "Motion" text NULL,
    "Source" text NULL,
    "LegisId" text NULL,
    "IsLive" boolean NOT NULL,
    "PrimaryLanguageId" integer NOT NULL,
    "EnteredBy" integer NOT NULL,
    "EnteredDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" integer NOT NULL,
    "LastUpdated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Amendment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Amendment_Language_PrimaryLanguageId" FOREIGN KEY ("PrimaryLanguageId") REFERENCES "Language" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "RolesId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("RolesId", "UserId"),
    CONSTRAINT "FK_UserRoles_Role_RolesId" FOREIGN KEY ("RolesId") REFERENCES "Role" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AmendmentBody" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AmendId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    "AmendBody" text NOT NULL,
    "AmendStatus" integer NOT NULL,
    "IsLive" boolean NOT NULL,
    "EnteredBy" integer NOT NULL,
    "EnteredDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" integer NOT NULL,
    "LastUpdated" timestamp without time zone NOT NULL,
    "Page" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AmendmentBody" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AmendmentBody_Amendment_AmendId" FOREIGN KEY ("AmendId") REFERENCES "Amendment" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AmendmentBody_Language_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Language" ("Id") ON DELETE CASCADE
);

INSERT INTO "Language" ("Id", "LanguageCode", "LanguageName")
VALUES (1, 'ENG', 'English');
INSERT INTO "Language" ("Id", "LanguageCode", "LanguageName")
VALUES (2, 'SPA', 'Spanish');
INSERT INTO "Language" ("Id", "LanguageCode", "LanguageName")
VALUES (3, 'FRA', 'French');

INSERT INTO "Role" ("Id", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name")
VALUES (1, -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'System Administrator');
INSERT INTO "Role" ("Id", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name")
VALUES (2, -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'Screen Controller');
INSERT INTO "Role" ("Id", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name")
VALUES (3, -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'Amendment Editor');
INSERT INTO "Role" ("Id", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name")
VALUES (4, -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'Translator');
INSERT INTO "Role" ("Id", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name")
VALUES (5, -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'Toast Notifications');

INSERT INTO "SystemSetting" ("Id", "EnteredBy", "EnteredDate", "Key", "LastUpdated", "LastUpdatedBy", "Value")
VALUES (1, -1, TIMESTAMP '2018-01-01 00:00:00', 'ShowDeafSigner', TIMESTAMP '2018-01-01 00:00:00', -1, '1');
INSERT INTO "SystemSetting" ("Id", "EnteredBy", "EnteredDate", "Key", "LastUpdated", "LastUpdatedBy", "Value")
VALUES (2, -1, TIMESTAMP '2018-01-01 00:00:00', 'ShowDeafSignerBox', TIMESTAMP '2018-01-01 00:00:00', -1, '1');
INSERT INTO "SystemSetting" ("Id", "EnteredBy", "EnteredDate", "Key", "LastUpdated", "LastUpdatedBy", "Value")
VALUES (3, -1, TIMESTAMP '2018-01-01 00:00:00', 'InvertedSlideText', TIMESTAMP '2018-01-01 00:00:00', -1, '1');

INSERT INTO "User" ("Id", "Email", "EnteredBy", "EnteredDate", "LastUpdated", "LastUpdatedBy", "Name", "Password", "RefreshToken", "RefreshTokenExpiryTime", "Username")
VALUES (1, 'admin@admin.com', -1, TIMESTAMP '2018-01-01 00:00:00', TIMESTAMP '2018-01-01 00:00:00', -1, 'Admin', '$2b$12$HbvEC6UaeXiGGlv8ztvzL.SB6oBXKi2QoBkJsjwQvDJGpQ59CmWrq', NULL, TIMESTAMP '-infinity', 'admin');

INSERT INTO "UserRoles" ("RolesId", "UserId")
VALUES (1, 1);

CREATE INDEX "IX_Amendment_PrimaryLanguageId" ON "Amendment" ("PrimaryLanguageId");

CREATE INDEX "IX_AmendmentBody_AmendId_LanguageId" ON "AmendmentBody" ("AmendId", "LanguageId");

CREATE INDEX "IX_AmendmentBody_LanguageId" ON "AmendmentBody" ("LanguageId");

CREATE UNIQUE INDEX "IX_SystemSetting_Key" ON "SystemSetting" ("Key");

CREATE INDEX "IX_UserRoles_UserId" ON "UserRoles" ("UserId");

SELECT setval(
    pg_get_serial_sequence('"Language"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Language") + 1,
        nextval(pg_get_serial_sequence('"Language"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Role"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Role") + 1,
        nextval(pg_get_serial_sequence('"Role"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"SystemSetting"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SystemSetting") + 1,
        nextval(pg_get_serial_sequence('"SystemSetting"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"User"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "User") + 1,
        nextval(pg_get_serial_sequence('"User"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230315050033_Initial', '7.0.4');

COMMIT;

